### ISSUE TITLE
Ошибка в описании функции reject

### ISSUE THREAD

**Issue by MoonlightOwl** [DenisHomich/underscorejs-RU#12]
"Возвращает массив, содержащий все значения list, за исключением элементов, для которых функция iterator вернула значение, **отличное от** true."

Надо исправить на
"Возвращает массив, содержащий все значения list, за исключением элементов, для которых функция iterator вернула значение true."

Иначе смысл прямо противоположный =)

**Comment by grandmaster8** [comment]
На него забили похоже, год коммитов не было.

**Comment by hogart** [comment]
Пришлите пулл-реквест, смерджим:)

**Comment by MoonlightOwl** [comment]
Сделано. #13

**Comment by hogart** [comment]
Спасибо.
